#!/usr/bin/perl

use strict;
local *FH;

print "#### This script uses a heuristic, so may not be accurate\n";

my @list = `ps afhx -o pid,command`;
foreach my $line (@list) {
	my($pid, $reset) = ($line =~ /^\s*(\d+)\s+(.*)/);
	my $bitness = 0;

	if (!open(FH, "</proc/$pid/maps")) {
		next;
	}

	while (defined(my $subline = <FH>)) {
		$subline =~ /^([0-9a-f]+)/i;
		if ($bitness < length($1)) {
			$bitness = length($1);
		}
	}

	printf "[%2s] %s", $bitness == 0 ? "--" : 4 * $bitness, $line;
	close FH;
}
