.TH diff2php 1 "2008\-02\-06" "hxtools" "hxtools"
.SH Name
.PP
diff2php - transform a patch into a self\-serving PHP file
.SH Syntax
.PP
\fBdiff2php\fP \fIfile\fP
.SH Description
.PP
Create a PHP file from a patch. The PHP file will server the patch as colored
HTML when viewed, or alternatively as raw text/plain for downloading.
