.TH extract_f3pod 1 "2008-11-11" "hxtools" "hxtools"
.SH Name
.PP
extract_f3pod \(em extract Fury3 POD files
.SH Syntax
.PP
\fBextract_f3pod\fP [\fB\-Lv\fP] [\fB\-C\fP \fIdir\fP] [\fB\-f\fP \fIfile\fP]
.SH Description
.PP
Extracts all files in a Terminal Reality POD archive file.
.SH Options
.PP
Most of the options have been borrowed from \fBtar\fP(1).
.TP
\fB\-C\fP \fIdir\fP
Extract files into the directory \fIdir\fP. The default is into the current
directory.
.TP
\fB\-L\fP
Automatically lowercase filenames during extraction if they are all uppercase.
.TP
\fB\-f\fP \fIfile\fP
Extract from \fIfile\fP. Defaults to stdin.
.TP
\fB\-v\fP
Be verbose \(em print file info and filenames.
.SH Supported Games
.IP "\(bu" 4
Terminal Velocity
.IP "\(bu" 4
Fury 3
.IP "\(bu" 4
Hellbender
