.TH fd0ssh 1 "2008\-04\-06" "hxtools" "hxtools"
.SH Name
.PP
fd0ssh - pipe for password\-over\-stdin support to ssh
.SH Syntax
.PP
\fBfd0ssh\fP \fImount_command\fP
.SH Description
.PP
This is a wrapper for ssh which reads the password from stdin and sets things
up so that ssh will recall the wrapper to get the password, which will be read
from the parent process using a pipe.
.PP
It is used by \fBpam_mount\fP(8) to mount SSH\-based filesystems, such as ccgfs
and sshfs.
.SH "See also"
.PP
Idea by John S. Skogtvedt, http://www.debian\-administration.org/articles/587
