.TH filenameconv 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
.PP
filenameconv \(em convert file name encoding
.SH Syntax
.PP
\fBfilenameconv\fP [\fB\-Y\fP] \fB\-f\fP \fIcharset\fP \fB\-t\fP \fIcharset\fP
\fIdirectory\fP...
.SH Description
.PP
Convert filenames on the whole filesystem between two charsets. The selected
charsets must be supported by the \fBiconv\fP(1) program! Also note that
\fBall\fP source filenames must have the same encoding or translation errors
may occur.
.SH Options
.TP
\fB\-f\fP \fIcharset\fP
The charset which your filenames are currently encoded in.
.TP
\fB\-t\fP \fIcharset\fP
The charset you want to have the filenames to be in afterwards.
.TP
\fB\-Y\fP
Do the operation! Process the files instead of just showing what would be done.
(Not specifying this would make for a dry run.)
.SH Example
.PP
.nf
filenameconv \-f iso\-8859\-1 \-t utf\-8 .
.fi
