.TH flv2avi 1 "2008-04-06" "hxtools" "hxtools"
.SH Name
.PP
flv2avi \(em repackage Flash video into an AVI container with PCM audio
.SH Syntax
.PP
\fBflv2avi\fP \fIfile\fP...
.SH Description
.PP
MPlayer sometimes has problems keeping A-V sync in FLV files. A workaround the
hxtools author has found is to convert the audio stream to PCM.
