.TH fxterm 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
.PP
fxterm \(em start xterm with sane settings
.SH Syntax
.PP
\fBfxterm\fP [\fB\-j\fP] [\fB\-f\fP \fIfont\fP]
.SH Description
.PP
A shortcut for the author's favorite xterm parameters:
.IP "\(bu" 4
black background (slightly blue tint), gray background (VGA console)
.IP "\(bu" 4
80x25 (VGA console)
.IP "\(bu" 4
visual bell
.IP "\(bu" 4
no scrollbar
.IP "\(bu" 4
optional font
.SH Options
.TP
\fB\-f\fP \fIfont\fP
Font to start with.
.TP
\fB\-j\fP
Enable SCIM as input interface.
