.TH "git\-export\-patch" 1 "2009\-05\-25" "hxtools" "hxtools"
.SH Name
.PP
git\-export\-patch - produce perfect patch from git comits for mail submission
.SH Syntax
.PP
\fBgit\-export\-patch\fP [\fB\-\-tsvn\fP] \fIcommit_range\fP
.SH Description
.PP
Exports the given commit-range as files which can then be sent using your
favorita MUA.
.SH Options
.PP
.TP
\fB\-\-tsvn\fP
Produce patches in TortoiseSVN format. This adds a normally redundant filler to
the end of git-produced "\-\-\-" lines, because TSVN so incredibly wants to see
a tabulator or otherwise thinks there is no file in the patch.
Furthermore, the patch is output in \-p0 mode rather than the default \-p1.
.SH Examples
.PP
.nf
	git\-export\-patch HEAD~10..HEAD
.fi
.PP
will export the last ten commits. As usual with git, a commit range a..b
does NOT include a, so you will be wanting to specify a^..b to get the
"inclusive" behavior.
