.TH git\-track 1 "2008\-11\-18" "hxtools" "hxtools"
.SH Name
.PP
git\-track - set up branch for tracking a remote
.SH Syntax
.PP
\fBgit\-track\fP \fIremote\fP\fB/\fP\fIbranch\fP
.SH Description
.PP
Wrapper to call
.PP
.nf
	git config branch.<current>.remote = <nickname>
	git config branch.<current>.merge = <remote-ref>
.fi
