.TH git-lemon 1 "2008-11-11" "hxtools" "hxtools"
.SH Name
.PP
git-lemon \(em don't just pick cherries, but take it all (cherry-pick a commit range)
.SH Syntax
.PP
\fBgit\-lemon\fP \fIcommit_range\fP
.SH Description
.PP
git-lemon simply calls git-cherry-pick in a loop, analogous to squeezing
more than just one drop out of a lemon.
