.TH gpsh 1 "2010-11-30" "hxtools" "hxtools"
.SH Name
.PP
gpsh \(em grep and play my audio files from shell
.SH Syntax
.PP
\fBgpsh\fP [\fB\-F\fP \fIindex.m9u\fP] [\fB\-blqxz\fP] \fIpatterns\fP...
.SH Description
.PP
Greps the master index file by the specified patterns and plays back any
matching entries (using external programs: mplayer, timidity). It expressly
supports jumping into subtracks in mixes.
.PP
When no pattern is given, all files are selected.
.SH Options
.TP
\fB\-F\fP \fIindex.m9u\fP
Give the path to the master index file. It is just a dump of the internal array
state in Perl form, so M9U is not exactly a format of its own. This index
contains: filename, and title and offset (for subtracks inside mixes).
.TP
\fB\-b\fP
Do index rebuild in foreground.
.TP
\fB\-l\fP
Only grep the database.
.TP
\fB\-q\fP
Do not print time position while playing (only timidity).
.TP
\fB\-x\fP
Force creating MKA-indexed files everytime.
.TP
\fB\-z\fP
Do not shuffle the play queue.
.SH Index
.PP
gpsh keeps an index cache, and refreshes it in the background when it is older
than a day. If there is no index yet, playing files will be delayed until it
exists.
.SH Tracklists for mixes
.PP
gpsh scans all .txt files for the following pattern used to denote a subtrack
in a big mix of the same basename:
.PP
/^\[(?:(\d+):)?(\d+):(\d+)\](.*)/
.PP
Example: Audio file: "DJ Doboy - Trancequility volume 01.mp3",
Tracklist: "DJ Doboy - Trancequility volume 01.txt",
TL content: "[48:29] Paul van Dyk - For an angel".
.SH Regex search
.PP
gpsh uses a Perl regular expression search across file name (mix name, if any)
and subtrack name.
.PP
Example: gpsh 'dj.doboy.*trancequility.*paul.van.dyk'
.PP
Would cause gpsh to search for all PVD tracks in Doboy's Trancequility
mixes. mplayer will be invoked on "DJ Doboy - Trancequility volume 01.mp3"
with automatic seeking to position 48:29, for example. Of course, just
specifying
.PP
gpsh 'dj.doboy.*trancequility'
.PP
Would select the grand mix and start at 00:00.
