.TH hxtools 7 "2008-11-11" "hxtools" "hxtools"
.SH Name
hxtools \(em Suite of various shell scripts and other stuff
.SH Description
.PP
\fBhxtools\fP is Jan Engelhardt's accumulated tool collection.
.SH Paths
.PP
Usually, the hxtools suite is installed in /opt/hxtools, with the more
important programs in /opt/hxtools/bin, and additional ones in
/opt/hxtools/libexec.
.SH Components
.PP
\fBbsvplay\fP(1) \(en convert BASICA music files to PCM
.PP
\fBcctypeinfo\fP(1) \(en show sizes of C types on the implementation it was
compiled with
.PP
\fBcheckbrack\fP(1) \(en check parenthesis and bracket count
.PP
\fBcwdiff\fP(1) \(en run wdiff with color
.PP
\fBdeclone\fP(1) \(en break hardlinks
.PP
\fBdiff2php\fP(1) \(en transform patch to self\-serving PHP file
.PP
\fBdoxygen\-kernel\-filter\fP(1) \(en a doxygen filter for doxygen to
understand KernelDoc
.PP
\fBextract_d3pkg\fP(1) \(en extract Descent3 PKG files
.PP
\fBextract_dxhog\fP(1) \(en extract Descent HOG files
.PP
\fBextract_f3pod\fP(1) \(en extract Fury3 POD files
.PP
\fBextract_qupak\fP(1) \(en extract Quake2 PACK files
.PP
\fBfd0ssh\fP(1) \(en pipe for password-over-stdin support to ssh
.PP
\fBfduphl\fP(1) \(en find duplicate files and hardlink them
.PP
\fBfilenameconv\fP(1) \(en convert file name encoding
.PP
\fBfnt2bdf\fP(1) \(en convert VGA raw fonts to X11 BDF
.PP
\fBfxterm\fP(1) \(en start xterm with sane settings
.PP
\fBgit\-author\-stat\fP(1) \(en show commit author statistics of a git repository
.PP
\fBgit\-blame\-stat\fP(1) \(en show per-line author statistics of a git
repository
.PP
\fBgit\-export\-patch\fP(1) \(en produce perfect patch from git comits for mail
submission
.PP
\fBgit\-forest\fP(1) \(en display the commit history forest
.PP
\fBgit\-lemon\fP(1) \(en don't just pick cherries, but take it all (cherry-pick a
commit range)
.PP
\fBgit\-new\-root\fP(1) \(en start a new branch with a new history root
.PP
\fBgit\-revert\-stats\fP(1) \(en show reverting statistics of a git repository
.PP
\fBgit\-track\fP(1) \(en set up branch for tracking a remote
.PP
\fBgpsh\fP(1) \(en grep tracklists and play audio files
.PP
\fBgraph\-fanout\fP(1) \(en fan a tree (for graphviz)
.PP
\fBgraph\-lchain\fP(1) \(en remove circles in graphs using longest-chaining
method
.PP
\fBlogontime\fP(8) \(en show cumulative logon time from wtmp
.PP
\fBmailsplit\fP(1) \(en split an mbox into single files
.PP
\fBman2html\fP(1) \(en convert nroff manpages to HTML
.PP
\fBmod2ogg\fP(1) \(en wrapper for module to OggVorbis transcoding
.PP
\fBmpg2ogg\fP(1) \(en wrapper for mass mp3 to OggVorbis transcoding
.PP
\fBnetload\fP(8) \(en show utilization of network interface
.PP
\fBnewns\fP(8) \(en clone current filesystem namespace and start a process
.PP
\fBofl\fP(1) \(en open file lister
.PP
\fBomixer\fP(1) \(en volume control using the OSS Sound API
.PP
\fBoplay\fP(1) \(en raw PCM playback using the OSS Sound API
.PP
\fBorec\fP(1) \(en raw PCM recording using the OSS Sound API
.PP
\fBpaddrspacesize\fP(1) \(en print size of processes' address spaces
.PP
\fBpesubst\fP(1) \(en perl-regexp stream substitution (replaces sed for
substitutions)
.PP
\fBpmap_dirty\fP(1) \(en print amount of dirty pages of a process
(somewhat indicative of its memory use)
.PP
\fBpng2wx.pl\fP(1) \(en transform arbitrary files into C++ files for wxWidgets
.PP
\fBprintcaps\fP(1) \(en print currently active process capabilities
.PP
\fBproc_iomem_count\fP(1) \(en show MMIO region sizes
.PP
\fBproc_stat_signal\fP(1) \(en decode /proc/self/stat for signal status
.PP
\fBpshtreads\fP(1) \(en alternative experiment to ps(1) involving thread
display
.PP
\fBqplay\fP(1) \(en convert QBASIC play strings to PCM
.PP
\fBqtar\fP(1) \(en faster interface to tar with file ordering
.PP
\fBraregetty\fP(8) \(en local login program for remote hosts
.PP
\fBrecursive_lower\fP(1) \(en recursively lowercase all filenames
.PP
\fBrpmdep.pl\fP(1) \(en read RPM dependencies and output a graph
.PP
\fBsourcefuncsize\fP(1) \(en statistical analysis of code
.PP
\fBspec\-beautifier\fP(1) \(en program to clean up RPM .spec files
.PP
\fBstxdb\fP(1) \(en A/V file database
.PP
\fBsu1\fP(8) \(en what sudo should have done
.PP
\fBsysinfo\fP(1) \(en print IRC\-style system information banner
.PP
\fBtailhex\fP(1) \(en hex dumper with tail\-following support
.PP
\fButmp_register\fP(1) \(en make entries in the utmp/wtmp database
.PP
\fBvcsaview\fP(8) \(en display a screen dump in VCSA format
.PP
\fBvfontas\fP(1) \(en VGA font file assembler
.PP
\fBwavdiff\fP(1) \(en proof-of-concept raw PCM deltifier
.PP
\fBwktimer\fP(1) \(en work timer
.PP
\fBxcp\fP(1) \(en proof-of-concept cp(1) with alternate copying mechanisms
.PP
\fBxfs_irecover\fP(8) \(en recover lost inodes from XFS filesystems
.SH Removed components
.PP
Some helpers have been recently removed because they have found better
equivalents.
.PP
\fBflv2avi\fP. MPlayer-1.0rc4_r32749 (perhaps earlier) no longer shows the
issue. For affected versions, try using ffmpeg for remuxing.
.PP
\fBflv2mka\fP. Replacable by `ffmpeg -i input -vn -acodec copy out.mka`.
.PP
\fBgit-lemon\fP. `git cherry-pick` can handle ranges itself as of git 1.7.2.
.PP
\fBhtruncate\fP. Replacable by truncate(1) in coreutils 7.x and up.
.PP
\fBkps\fP. Now known as \fBpsthreads\fP(1).
.PP
\fBln2\fP. Replacable by `cp -l`.
.PP
\fBtestdl\fP. Replacable by `ldd -r`.
