.TH hxtools 7 "2008-11-11" "hxtools" "hxtools"
.SH Name
hxtools \(em Suite of various shell scripts and other stuff
.SH Description
.PP
\fBhxtools\fP is Jan Engelhardt's accumulated tool collection.
.SH Paths
.PP
Usually, the hxtools suite is installed in /opt/hxtools, with the more
important programs in /opt/hxtools/bin, and additional ones in
/opt/hxtools/libexec.
.SH Components
.IP "\(bu" 4
\fBbsvplay\fP(1) \(en convert BASICA music files to PCM
.IP "\(bu" 4
\fBcheckbrack\fP(1) \(en check parenthesis and bracket count
.IP "\(bu" 4
\fBcwdiff\fP(1) \(en run wdiff with color
.IP "\(bu" 4
\fBdeclone\fP(1) \(en break hardlinks
.IP "\(bu" 4
\fBdiff2php\fP(1) \(en transform patch to self\-serving PHP file
.IP "\(bu" 4
\fBextract_d3pkg\fP(1) \(en extract Descent3 PKG files
.IP "\(bu" 4
\fBextract_dxhog\fP(1) \(en extract Descent HOG files
.IP "\(bu" 4
\fBextract_f3pod\fP(1) \(en extract Fury3 POD files
.IP "\(bu" 4
\fBextract_qupak\fP(1) \(en extract Quake2 PACK files
.IP "\(bu" 4
\fBfd0ssh\fP(1) \(en pipe for password\-over\-stdin support to ssh
.IP "\(bu" 4
\fBfilenameconv\fP(1) \(en convert file name encoding
.IP "\(bu" 4
\fBflv2avi\fP(1) \(en repackage Flash video into an AVI container with PCM audio
.IP "\(bu" 4
\fBfnt2bdf\fP(1) \(en convert VGA raw fonts to X11 BDF
.IP "\(bu" 4
\fBfxterm\fP(1) \(en start xterm with sane settings
.IP "\(bu" 4
\fBgit\-author\-stat\fP(1) \(en show commit author statistics of a git repository
.IP "\(bu" 4
\fBgit\-export\-patch\fP(1) \(en produce perfect patch from git comits for mail
submission
.IP "\(bu" 4
\fBgit\-forest\fP(1) \(en display the commit history forest
.IP "\(bu" 4
\fBgit\-lemon\fP(1) \(en don't just pick cherries, but take it all (cherry-pick a
commit range)
.IP "\(bu" 4
\fBgit\-revert\-stats\fP(1) \(en show reverting statistics of a git repository
.IP "\(bu" 4
\fBgit\-track\fP(1) \(en set up branch for tracking a remote
.IP "\(bu" 4
\fBlogontime\fP(8) \(en show cumulative logon time from wtmp
.IP "\(bu" 4
\fBlongjumpcd\fP(1) \(en helper for parallel directory jump (extended cd)
.IP "\(bu" 4
\fBmailsplit\fP(1) \(en split an mbox into single files
.IP "\(bu" 4
\fBman2html\fP(1) \(en convert nroff manpages to HTML
.IP "\(bu" 4
\fBmod2ogg\fP(1) \(en wrapper for module to OggVorbis transcoding
.IP "\(bu" 4
\fBmpg2ogg\fP(1) \(en wrapper for mass mp3 to OggVorbis transcoding
.IP "\(bu" 4
\fBnetload\fP(8) \(en show utilization of network interface
.IP "\(bu" 4
\fBnewns\fP(8) \(en clone current filesystem namespace and start a process
.IP "\(bu" 4
\fBofl\fP(1) \(en open file lister
.IP "\(bu" 4
\fBomixer\fP(1) \(en volume control using the OSS Sound API
.IP "\(bu" 4
\fBoplay\fP(1) \(en raw PCM playback using the OSS Sound API
.IP "\(bu" 4
\fBorec\fP(1) \(en raw PCM recording using the OSS Sound API
.IP "\(bu" 4
\fBpesubst\fP(1) \(en perl-regexp stream substitution (replaces sed for
substitutions)
.IP "\(bu" 4
\fBplayalot\fP(1) \(en wrapper for programs to play about everything
.IP "\(bu" 4
\fBqplay\fP(1) \(en convert QBASIC play strings to PCM
.IP "\(bu" 4
\fBraregetty\fP(8) \(en local login program for remote hosts
.IP "\(bu" 4
\fBrecursive_lower\fP(1) \(en recursively lowercase all filenames
.IP "\(bu" 4
\fBsourcefuncsize\fP(1) \(en statistical analysis of code
.IP "\(bu" 4
\fBstxdb\fP(1) \(en A/V file database
.IP "\(bu" 4
\fBsysinfo\fP(1) \(en print IRC\-style system information banner
.IP "\(bu" 4
\fBtailhex\fP(1) \(en hex dumper with tail\-following support
.IP "\(bu" 4
\fBtestdl\fP(1) \(en test whether shared libraries load
.IP "\(bu" 4
\fBtruncate\fP(1) \(en truncate files to specific size
.IP "\(bu" 4
\fButmp_register\fP(1) \(en make entries in the utmp/wtmp database
.IP "\(bu" 4
\fBvcsaview\fP(8) \(en display a screen dump in VCSA format
.IP "\(bu" 4
\fBvfontas\fP(1) \(en VGA font file assembler
.IP "\(bu" 4
\fBwavdiff\fP(1) \(en proof-of-concept raw PCM deltifier
.IP "\(bu" 4
\fBwktimer\fP(1) \(en work timer
.IP "\(bu" 4
\fBxcp\fP(1) \(en proof-of-concept cp(1) with alternate copying mechanisms
