.TH hxtools 7 "2008\-11\-11" "hxtools" "hxtools"
.SH Name
hxtools - Suite of various shell scripts and other stuff
.SH Description
.PP
\fBhxtools\fP is Jan Engelhardt's accumulated tool collection.
.SH Components
.IP "\(bu" 4
\fBbsvplay\fP(1) - convert BASICA music files to PCM
.IP "\(bu" 4
\fBcheckbrack\fP(1) - check parenthesis and bracket count
.IP "\(bu" 4
\fBcwdiff\fP(1) - run wdiff with color
.IP "\(bu" 4
\fBdeclone\fP(1) - break hardlinks
.IP "\(bu" 4
\fBdiff2php\fP(1) - transform patch to self\-serving PHP file
.IP "\(bu" 4
\fBextract_d3pkg\fP(1) - extract Descent3 PKG files
.IP "\(bu" 4
\fBextract_dxhog\fP(1) - extract Descent HOG files
.IP "\(bu" 4
\fBextract_f3pod\fP(1) - extract Fury3 POD files
.IP "\(bu" 4
\fBextract_qupak\fP(1) - extract Quake2 PACK files
.IP "\(bu" 4
\fBfd0ssh\fP(1) - pipe for password\-over\-stdin support to ssh
.IP "\(bu" 4
\fBfilenameconv\fP(1) - convert file name encoding
.IP "\(bu" 4
\fBflv2avi\fP(1) - repackage Flash video into an AVI container with PCM audio
.IP "\(bu" 4
\fBfnt2bdf\fP(1) - convert VGA raw fonts to X11 BDF
.IP "\(bu" 4
\fBgit-forest\fP(1) - display the commit history forest
.IP "\(bu" 4
\fBgit-revert-stats\fP(1) - show reverting statistics
.IP "\(bu" 4
\fBlogontime\fP(1) - show cumulative logon time from wtmp
.IP "\(bu" 4
\fBlongjumpcd\fP(1) - helper for parallel directory jump (extended cd)
.IP "\(bu" 4
