.TH mpl 1 "2008\-12\-31" "hxtools" "hxtools"
.SH Name
.PP
mpl - wrapper for programs to play about everything
.SH Syntax
.PP
\fBmpl\fP [\fB\-aqz\fP]
.SH Description
.PP
Plays the given files, using external programs. It is some sort of simple
launcher for the various file types, such as OGG, UMX, MID/MOD/XM/IT/S3M, MP3.
.SH Options
.TP
\fB\-a\fP
Display full instrumental sheet (only timidity)
.TP
\fB\-q\fP
Do not print time position while playing (only timidity)
.TP
\fB\-z\fP
Shuffle file list
