.TH newns 8 "2008-11-11" "hxtools" "hxtools"
.SH Name
.PP
newns \(em clone current filesystem namespace and start a process
.SH Syntax
.PP
\fBnewns\fP [\fIprogram args\fP...]
.SH Description
.PP
Clones the current filesystem namespace and execs to a program. If no program
is specified, the bash shell will be started.
.SH "See also"
.PP
\fBclone\fP(2) and the CLONE_NEWNS flag.
.PP
newns's invocation works like \fBchroot\fP(8).
