.TH png2wx 1 "2008-11-28" "hxtools" "hxtools"
.SH Name
.PP
png2wx \(em embed image files into C++ source for wxWidgets
.SH Syntax
.PP
\fBpng2wx.pl\fP [\fB\-M\fP \fImarker\fP] \fB\-C\fP \fIoutput.cpp\fP
\fB\-H\fP \fIoutput.hpp\fP
.SH Description
.PP
Embeds image files into a C++ source file as wxBitmaps so that the images can
subsequently be used within wxWidgets projects.
