.TH raregetty 8 "2008\-02\-06" "hxtools" "hxtools"
.SH Name
.PP
raregetty - local login program for remote hosts
.SH Syntax
.PP
\fBraregetty\fP [\fB\-cn\fP] [\fB\-d\fP \fIdefaulthost\fP] [\fB\-h\fP
\fIhost\fP] \fItty\fP
.SH Description
.PP
A simple login prompt which allows connecting to remote hosts. This is useful
for diskless stations' consoles (tty1-...) to log onto a server.
.SH Options
.TP
\fB\-c\fP
Clear screen before displaying "login:".
.TP
\fB\-d\fP
Specify a default host, which will be used if none is entered during login
session.
.TP
\fB\-h\fP
If specified, raregetty will not allow logging into any machine other than the
one specified by \-d.
.TP
\fB\-n\fP
Do not reopen tty devices. This is for debugging.

