.TH recursive_lower 1 "2008-11-11" "hxtools" "hxtools"
.SH Name
.PP
recursive_lower \(em recursively lowercase all filenames
.SH Syntax
.PP
\fBrecursive_lower\fP \fIdirectory\fP...
.SH Description
.PP
Dives into all specified directories and their subdirectories and translates
the the filename to all-lowercase.
