.TH spec-beautifier 1 "2010-12-01" "hxtools" "hxtools"
.SH Name
.PP
spec-beautifier \(em program to clean up RPM .spec files
.SH Syntax
.PP
\fBspec\-beautifier\fP [\fB\-d\fP|\fB\-r\fP] [\fIfile\fP...]
.SH Description
.PP
spec-beautifier checks .spec files, as used for rpmbuild(1), for
inconsistencies and corrects them where possible, or emits a warnings to
notify the user of required manual intervention.
.SH Options
.PP
Without any options, the files are processed and the result is written to
stdout (sort of a dry run).
.TP
\fB\-d\fP
Instead of printing the substituted text, print a diff-like output with "-"
and "+" lines, showing the differences applied.
.TP
\fB\-r\fP
Not so dry run: Modify files in place.
