.TH sysinfo 1 "2008\-02\-06" "hxtools" "hxtools"
.SH Name
.PP
sysinfo - print IRC-style system information banner for bragging
.SH Syntax
.PP
\fBsysinfo\fP
.SH Description
.PP
Prints out an IRC\-style machine info, like:
.PP
[yaguchi.medozas.de] Linux 2.6.25.8\-jen67\-rt | AMD Athlon(tm) XP 2000+ 1666
MHz | Load: 0.17 Tasks: 232 | MemUse: 238/753MB | DiskUse: 184/227GB | Gfx:
nVidia Corporation NV11 [GeForce2 MX/MX 400] (rev a1) @ 2944x2208
.PP
The load number is the EWMA over the last 60 seconds; Memory and disk are:
used/total; (\fBNOT\fP free/total) The @\fIxres\fPx\fIyres\fP is only available
if $DISPLAY is set and valid.  \fIxres\fP and \fIyres\fP will be the dimensions
of the _virtual_ size, not the resolution.
