.TH tailhex 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
.PP
tailhex \(em hex dumper with tail-following support
.SH Syntax
.PP
\fBtailhex\fP [\fB\-Qaf\fP] [\fB\-B\fP \fIbytes\fP] [\fB\-e\fP \fIstart\fP]
\fIfile\fP
.SH Description
.PP
About the same as `od \-x` (tailhex was written before the author was aware of
`hexdump \-C`), with 64-bit support, readable printout and tail following.
.SH Options
.TP
\fB\-B\fP \fIbytes\fP
Buffer and window width.
.TP
\fB\-Q\fP
Use 64-bit pos numbers beginning from 0.
.TP
\fB\-a\fP
Approximate position start.
.TP
\fB\-e\fP \fIstart\fP
Exact position start at.
.TP
\fB\-f\fP
Retry at EOF (tail follow mode).
