.TH testdl 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
.PP
testdl \(em test whether shared libraries load
.SH Syntax
.PP
\fBtestdl\fP \fIlibrary\fP...
.SH Description
.PP
Tries to load bare libraries and check for missing symbols.
Note that this will not work on shared libraries that reference symbols from
the main program that have been exported using the \-rdynamic linker flag.
(Because testdl does not load the main program.)
