.TH vfontas 1 "2003\-03\-08" "hxtools" "hxtools"
.SH Name
.PP
vfontas - VGA font file assembler
.SH Syntax
.PP
\fBvfontas\fP [\fB\-E\fP] [\fB\-D\fP \fIdirectory\fP] [\fB\-c|\-\-create\fP]
[\fB\-f\fP \fIfile\fP] [\fB\-x|\-\-extract\fP]
.SH Description
.PP
VFontAS (VGA font file assembler). This small utility works on 8x16x256 bit
raw font files (FNT). It can extract the chars from a FNT, that is, convert
them to a textual bitmap, and merge them back; mainly to create fonts.
.SH Syntax
.TP
\fB\-D\fP \fIdirectory\fP
Directory to read/write glyphs from/to.
.TP
\fB\-E\fP
Create an empty font file.
.TP
\fB\-c\fP, \fB--create\fP
Create a new FNT file by readnig all glyphs from the directory specified by
\-D.
.TP
\fB\-f\fP \fIfile\fP
Read/write from/to the VGA font stored in \fIfile\fP.
.TP
\fB\-x\fP, \fB\-\-extract\fP
Extract the VGA font file's glyphs into the directory specified by \-D.
.PP
Only one of \-E, \-c or \-x can be specified.
