.TH wavdiff 1 "2008\-11\-11" "hxtools" "hxtools"
.SH Name
.PP
wavdiff - proof\-of\-concept WAV deltifier
.SH Syntax
.PP
\fBwavdiff\fP \fIfile1\fP \fIfile2\fP \fB>\fP\fIfile3\fP
.SH Description
.PP
wavdiff will compute the arithmetic difference between the raw PCM files
\fIfile1\fP and \fIfile2\fP and write it to stdout. This allows to make the
degradation that inherently comes with lossy audio formats, audible.
.SH Examples
.PP
.nf
	oggenc -q0 -o test.ogg test.wav;
	oggdec -o test2.wav test.ogg;
	wavdiff test.wav test2.wav >delta.wav;
.fi
