.TH wktimer 1 "2008-02-06" "hxtools" "hxtools"
.SH Name
.PP
wktimer \(em work timer
.SH Syntax
.PP
\fBwktimer\fP [\fB\-FHiqs\fP] [\fB\-A\fP \fIname\fP] [\fB\-D\fP \fIname\fP]
[\fB\-L\fP [\fIname\fP]] [\fB\-S\fP \fIname\fP] [\fB\-W\fP \fIname\fP]
[\fB\-t\fP \fIfile\fP]
.SH Description
.PP
wktimer provides a small timestamping utility with second-granularity. Useful
to record your time as a Consultant.
.SH Options
.TP
\fB\-A\fP \fIname\fP
Create timer or restamp an existing timer's start time.
.TP
\fB\-D\fP \fIname\fP
Delete given timer.
.TP
\fB\-F\fP
Flush timer table (delete all timers).
.TP
\fB\-H\fP
Do not show header when printing the table with \-L.
.TP
\fB\-L\fP [\fIname\fP]
List specific timer (or all timers if no name given).
.TP
\fB\-S\fP \fIname\fP
Stop timer or restamp existing timer's stop time.
.TP
\fB\-W\fP \fIname\fP
Switch to timer (deactive all timers and resume given timer).
.TP
\fB\-i\fP
Show I-Start when printing the table with \-L.
.TP
\fB\-q\fP
Be quiet.
.TP
\fB\-s\fP
Show Cumulative and Elapsed time in seconds.
.TP
\fB\-t\fP \fIfile\fP
Use timer file (rather than ~/.timers).
.SH Notes
.PP
Restamping the start mark of a timer will add the elapsed time to the
cumulative count.
.PP
Restamping the stop mark of a timer will extend the elapsed time
(and thus, cumulative time) to "now".
