#!/bin/bash
#
#	recursive_lower
#	written by Jan Engelhardt <jengelh [at] medozas de>, 2004 - 2007
#	http://jengelh.medozas.de/
#	released in the Public Domain
#

descend_into()
{
	for src in "$@"; do
		dest="`echo -en \"$src\" | tr A-Z a-z`";
		mv "$src" "$id" && \
		mv "$id" "$dest";
		echo "$src" "->" "$dest";
		if [ -d "$src" -o -d "$dest" ]; then
			descend_into "$dest"/*;
		fi;
	done;
	return;
}

id=`mktemp -u .tmp.$$.XXXXXXXX`;
descend_into "$@";
